### ISSUE TITLE
Failed to execute make first-run

### ISSUE THREAD

**Issue by bcicc** [cohere-ai/cohere-toolkit#730]
### What is the issue?

When running `make first-run` on Ubuntu 24.04, an error occurs installing the backend as you can see below.

Traceback:
```
Installing the current project: backend (0.1.0)
poetry run python3 src/backend/cli/main.py
/home/saguaro/miniconda3/envs/cohere-env-test/lib/python3.11/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/home/saguaro/dev/cohere-toolkit/src/backend/cli/main.py", line 19, in <module>
    from backend.config.deployments import (
  File "/home/saguaro/dev/cohere-toolkit/src/backend/config/deployments.py", line 4, in <module>
    from backend.model_deployments import (
  File "/home/saguaro/dev/cohere-toolkit/src/backend/model_deployments/__init__.py", line 1, in <module>
    from backend.model_deployments.azure import AzureDeployment
  File "/home/saguaro/dev/cohere-toolkit/src/backend/model_deployments/azure.py", line 5, in <module>
    from backend.chat.collate import to_dict
  File "/home/saguaro/dev/cohere-toolkit/src/backend/chat/collate.py", line 4, in <module>
    from backend.model_deployments.base import BaseDeployment
  File "/home/saguaro/dev/cohere-toolkit/src/backend/model_deployments/base.py", line 4, in <module>
    from backend.schemas.cohere_chat import CohereChatRequest
  File "/home/saguaro/dev/cohere-toolkit/src/backend/schemas/__init__.py", line 3, in <module>
    from backend.schemas.message import *
  File "/home/saguaro/dev/cohere-toolkit/src/backend/schemas/message.py", line 6, in <module>
    from backend.database_models.message import MessageAgent
  File "/home/saguaro/dev/cohere-toolkit/src/backend/database_models/__init__.py", line 8, in <module>
    from backend.database_models.database import *
  File "/home/saguaro/dev/cohere-toolkit/src/backend/database_models/database.py", line 13, in <module>
    engine = create_engine(
             ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/saguaro/miniconda3/envs/cohere-env-test/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/home/saguaro/miniconda3/envs/cohere-env-test/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 546, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/home/saguaro/miniconda3/envs/cohere-env-test/lib/python3.11/site-packages/sqlalchemy/engine/url.py", line 846, in make_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Expected string or URL object, got None
make[1]: *** [Makefile:69: setup] Error 1
make[1]: Leaving directory '/home/saguaro/dev/cohere-toolkit'
make: *** [Makefile:91: first-run] Error 2
```

**Comment by bcicc** [comment]
tried again on a fresh install on a new machine and got the same issue, not doing anything besides git clone and `make first-run`

**Comment by bcicc** [comment]
running `export DATABASE_URL="postgresql+psycopg2://postgre:postgre@localhost:5432/toolkit"` allowed me to get `make first-run` to work

**Comment by tianjing-li** [comment]
@bcicc thanks for bringing this up, can you change in src/backend/config if the configuration.yaml and secrets.yaml file were generated after running `make first-run`?

**Comment by tianjing-li** [comment]
I know there is a strange issue where cloning the repo generates an empty configuration.yaml and secrets.yaml _folders_ there, so the cli doesn't overwrite them and you never get the proper environment variables, let me know if that's what you see

**Comment by tylerjthomas9** [comment]
After running `make first-run`, here is what our `src/backend/config/ folder looks like: 

```bash
cohere-toolkit/src/backend/config$ ls -a
.  ..  auth.py  configuration.template.yaml  deployments.py  __init__.py  __pycache__  routers.py  secrets.template.yaml  settings.py  tools.py
```

There is no empty `configuration.yaml` or `secrets.yaml` folders/files that were generated. Just the template files from the repo. They are only created after manually exporting database url before running `make first-run`.

**Comment by tianjing-li** [comment]
@tylerjthomas9 got it, strange that the config files weren't properly generated after the CLI setup. You can create a `configuration.yaml` and `secrets.yaml` files and copy the template contents over
